// Atlas ChartDB – shared type definitions

/** Packed RGBA color as 32-bit integer (LE: R=bits 0-7, G=8-15, B=16-23, A=24-31) */
export type PackedColor = number;

/** Unix timestamp in milliseconds */
export type TimestampMs = number;

/** Chart types */
export enum ChartType {
  Candlestick = 0,
  Line        = 1,
  Area        = 2,
  OhlcBar     = 3,
  Volume      = 4,   // standalone volume-only view
  Scatter     = 5,
}

/** Dataset types */
export enum DatasetType {
  OHLCV      = 0,  // 48 bytes per record
  TimeValue  = 1,  // 16 bytes per record
}

/** Indicator types */
export enum IndicatorType {
  SMA  = 0,
  EMA  = 1,
  BB   = 2,   // Bollinger Bands
  RSI  = 5,
  MACD = 6,
}

/** A single OHLCV record */
export interface OhlcvRecord {
  timestamp: number;   // unix ms (safe as JS number up to 2^53)
  open:  number;
  high:  number;
  low:   number;
  close: number;
  volume: number;
}

/** A single time-value record */
export interface TimeValueRecord {
  timestamp: number;
  value: number;
}

/** Options for adding an indicator */
export interface IndicatorOptions {
  /** IndicatorType enum */
  type:    IndicatorType;
  /** Dataset to compute the indicator on */
  dsId:    number;
  /** Look-back period (e.g. 14 for RSI, 20 for BB) */
  period:  number;
  /** Packed RGBA draw color */
  color:   PackedColor;
  /** Extra param 1 (BB: stddev multiplier; MACD: fast period) */
  param1?: number;
  /** Extra param 2 (MACD: slow period) */
  param2?: number;
  /** Extra param 3 (MACD: signal period) */
  param3?: number;
}

/** View range */
export interface ViewRange {
  start: TimestampMs;
  end:   TimestampMs;
}

/** Price range */
export interface PriceRange {
  min: number;
  max: number;
}

/** The full set of WAT exports (generated by compile step) */
export interface AtlasWasmExports {
  memory: WebAssembly.Memory;
  init(width: number, height: number): void;
  set_canvas_size(width: number, height: number): void;
  get_fb_ptr(): number;
  get_fb_size(): number;
  set_theme(bg: number, grid: number, text: number, up: number, down: number, line: number): void;
  set_margins(left: number, top: number, right: number, bottom: number): void;
  set_show_volume(show: number, panelH: number): void;
  set_ind_panel(show: number, height: number): void;
  auto_scale_ind_panel(): void;
  clear(): void;
  render_chart(): void;
  set_active_ds(id: number): void;
  set_chart_type(type: number): void;
  set_view_range(start: bigint, end: bigint): void;
  auto_scale_price(): void;
  set_price_range(min: number, max: number): void;
  set_crosshair(x: number, y: number): void;
  begin_dataset(type: number): number;
  write_ohlcv(ts: bigint, open: number, high: number, low: number, close: number, vol: number): void;
  write_tv(ts: bigint, value: number): void;
  end_dataset(): void;
  load_bin(ptr: number, len: number): number;
  serialize_dataset(id: number, outPtr: number): number;
  get_ds_count(): number;
  get_ds_record_count(id: number): number;
  get_ds_time_start(id: number): bigint;
  get_ds_time_end(id: number): bigint;
  add_indicator(type: number, dsId: number, period: number, color: number,
    p1: number, p2: number, p3: number): number;
  remove_indicator(id: number): void;
  compute_indicators(): void;
  hit_test(x: number, y: number): number;
  get_ohlcv_at(id: number, idx: number, outPtr: number): number;
  x_to_time_export(x: number): bigint;
  y_to_price_export(y: number): number;
}

/** Events emitted by the chart */
export type AtlasChartEventMap = {
  hover:  CustomEvent<{ x: number; y: number; index: number; ts: number; price: number }>;
  click:  CustomEvent<{ x: number; y: number; index: number; ts: number; price: number }>;
  zoom:   CustomEvent<ViewRange>;
  pan:    CustomEvent<ViewRange>;
  resize: CustomEvent<{ width: number; height: number }>;
};
